### ISSUE TITLE
pushMotionProfileTrajectory throws a null pointer exception if TrajectoryPoint.timeDur is not set

### ISSUE THREAD

**Issue by ryegleason** [CrossTheRoadElec/Phoenix-frc-lib#18]
It should probably default to 0 instead of throwing a NPE in a separate thread and causing the Talon to not execute the profile.

**Comment by ozrien** [comment]
Generally you should fill every member of TrajectoryPoint to ensure proper operation.

Since a null timeDir is not a sensible value, throwing is probably best.   Although ideally the TrajectoryPoint constructor should fill all the values so the push routine doesn't throw if you create a new TP, and only fill the members you care about.  

However, I'm not sure what timeDur should default to, the ideal default value depends on whether you are using the base trajectory duration feature or not.

Regardless you should tell the software how fast you want to run your points or you will not get the result you expected.

**Comment by ozrien** [comment]
Issue added to our private tracker.

**Comment by JCaporuscio** [comment]
This has been fixed since 5.8.0
